### PR TITLE
Make repo into a python package and use scripts

### PR DESCRIPTION
**Pull request by VannTen**
motivated by #37

### CODE REVIEW

**Comment by VannTen** [comment]
Also, if we then calling the script using `python script.py`, we will need a deprecation period

**Comment by VannTen** [comment]
/hold

might do this as part of #37

**Comment by harshad16** [comment]
These changes, seems to be in https://github.com/thoth-station/document-sync-job/pull/37
shall we close this?

**Comment by VannTen** [comment]
Yep, it's fully included

/close

**Pull request closed without merging**
